name: Convert YAML to PDF

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pypandoc

    - name: Convert YAML to PDF
      run: |
        python -c "import pypandoc; pypandoc.convert_file('path/to/main.yml', 'pdf', outputfile='credit_score_default_model.pdf')"

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: yaml-pdf
        path: credit_score_default_model.pdf
